language: php
sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - setup=basic
    - setup=lowest
    - setup=stable

before_script:
  - travis_retry composer self-update
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-source --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -c phpunit.xml

matrix:
  allow_failures:
    - env: setup=lowest
  fast_finish: true
