language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  matrix:
    - setup=basic
    - setup=lowest
    - setup=stable

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -c phpunit.xml

matrix:
  allow_failures:
    - php: nightly
    - env: setup=lowest
  fast_finish: true
