language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  global:
    - setup=basic

services:
  - redis-server

before_install:
  - pecl install -f redis
  - travis_retry composer self-update

before_script:
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -c phpunit.xml

matrix:
  include:
    - php: 5.4
      env: setup=lowest
    - php: 5.4
      env: setup=stable
  allow_failures:
    - env: setup=stable
    - php: hhvm
  fast_finish: true
